#!/bin/bash
cd /tmp/rom # Depends on where source got synced

curl https://gist.githubusercontent.com/SuperCosmicBeing/c6db35d8abfa480e183a66b71ffca563/raw/3f5f1fc6d02ae767479bda37c04ea417a229f7eb/gms_full.mk >> gms_full.mk
mv gms_full.mk vendor/gms/
rm -rf device/generic/opengl-transport

# Normal build steps
. build/envsetup.sh
lunch derp_vince-user
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G 
ccache -o compression=true 
ccache -z

# Telegram send message helper method
tg(){
	bot_api=$bot_api 
	your_telegram_id=$1 
	msg=$2
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}
id=-1001273969756
tg $id "DerpFest Compile Status: STARTED!.
Started at:- $(date)."

#mka derp -j8 &
#sleep 95m
#kill %1
#ccache -s

mka derp -j8 

#uploads

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf

#up(){
#	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
#}

time rclone copy /tmp/rom/out/target/product/vince/D*.zip drive:DerpFest -P
time rclone copy /tmp/rom/out/target/product/vince/vince.json drive:DerpFest -P	# build json file
time rclone copy /tmp/rom/out/target/product/vince/DerpFest*.sha256sum drive:DerpFest -P	# Hash file
tg $id "DerpFest Compile Status: \`FINISHED!\`
Finished at:- \`$(date)\`.
Download Link: https://ancient-bush-fa07.010-hugo-ad.workers.dev/DerpFest/$(basename out/t*/p*/v*/D*.zip)
CCache Stats:-
\`$(ccache -s | sed -n -e "6,9 p" -e "9 q")\`"

ccache -s

cd /tmp

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

tg $id "DerpFest Compile Status:
ccache uploading started at:- $(date)."

time rclone copy ccache.tar.gz drive:ccache -P 

tg $id "DerpFest Compile Status:
ccache uploaded at:- $(date)."
