#!/bin/bash
git config --global  user.name "aseelsathar"
git config --global  user.email "aseelsathar@gmail.com"



# Fix TimeZone
sudo ln -snf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

#tg
tg(){
	bot_api=$bot_api 
	your_telegram_id=$1 
	msg=$2 
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}

id=272503335 
tg $id "vince_ROM _Compile _Status: TRIGGERED!.
Triggered _at:- $(date).
https://cirrus-ci.com/build/$CIRRUS_BUILD_ID
https://cirrus-ci.com/task/$CIRRUS_TASK_ID"

mkdir -p /tmp/rom 
cd /tmp/rom

repo init -q --no-repo-verify --depth=1 -u git://github.com/DotOS/manifest.git -b dot11 -g default,-device,-mips,-darwin,-notdefault

repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

git clone --depth=1 https://github.com/aseelps/device_xiaomi_vince-11 --single-branch -b enforcive device/xiaomi/vince
git clone --depth=1 https://github.com/aseelps/vendor_xiaomi_vince-11 --single-branch -b dot11 vendor/xiaomi/vince
git clone --depth=1 https://github.com/dotOS-Devices/android_kernel_xiaomi_vince  --single-branch -b dot11 kernel/xiaomi/vince

#hals
rm -rf hardware/qcom-caf/msm8996/audio &&  git clone https://github.com/aseelps/hardware_qcom_audio_msm8996-vince hardware/qcom-caf/msm8996-vince/audio
rm -rf hardware/qcom-caf/msm8996/media && git clone https://github.com/aseelps/hardware_qcom_media_msm8996-vince hardware/qcom-caf/msm8996-vince/media
rm -rf hardware/qcom-caf/msm8996/display &&  git clone https://github.com/aseelps/hardware_qcom_display_msm8996-vince hardware/qcom-caf/msm8996-vince/display

